name = "pospichame"
main = "src/worker.js"
compatibility_date = "2024-01-01"

[assets]
directory = "public"

[[kv_namespaces]]
binding = "TICKETS"
id = "a68011cded084fffa6106b7a55a8156d" # Nahraďte vlastním ID

[observability.logs]
enabled = true

# Sekce [vars] byla kompletně odstraněna
