name = "pospichame"
main = "worker.js" # Tady je ta změna
compatibility_date = "2024-10-01"

[assets]
directory = "public"

[[kv_namespaces]]
binding = "TICKETS"
id = "a68011cded084fffa6106b7a55a8156d"

[observability.logs]
enabled = true

# Tato část by měla zabránit mazání tajných klíčů při deployi
[vars]
TURNSTILE_SECRET = ""
SIGNING_SECRET = ""
TARGET_URL = ""
