name = "pospichame"
main = "src/index.ts"
compatibility_date = "2024-10-01"

[assets]
directory = "public"

[[kv_namespaces]]
binding = "TICKETS"
id = "a68011cded084fffa6106b7a55a8156d"

[observability.logs]
enabled = true
