name = "pospichame"
main = "src/index.ts"
compatibility_date = "2024-10-01"

[assets]
directory = "public"
# optional:
# binding = "ASSETS"        # jen pokud bys chtěl přistupovat k assetům z kódu přes env.ASSETS
# html_handling = "auto"    # default; nech klidně být

[[kv_namespaces]]
binding = "TICKETS"
id = "a68011cded084fffa6106b7a55a8156d"
